### ISSUE TITLE
Grub complains "error: overlap detected"

### ISSUE THREAD

**Issue by foxostro** [missimer/x86-64-kernel-boot#1]
I love the blog post! When trying to run the example code, I ran into a problem where the bootloader would report "error: overlap detected" and refuse to load the image. It seems that removing the .eh_frame section fixes this problem.

Patch:
```
diff --git a/kernel/kernel.ld b/kernel/kernel.ld
index 7e80e44..bd78f2e 100644
--- a/kernel/kernel.ld
+++ b/kernel/kernel.ld
@@ -57,10 +57,7 @@ SECTIONS
     *(.bss)
   }

-  . = ALIGN(0x1000);
-  .eh_frame (NOLOAD) : { *(.eh_frame) } : NONE
-
   _kernel_virtual_end = .;

-  _kernel_physical_end = (LOADADDR (.eh_frame) + SIZEOF (.eh_frame) + 0xFFF) & 0xFFFFFFFFFFFFF000;
+  _kernel_physical_end = (LOADADDR (.bss) + SIZEOF (.bss) + 0xFFF) & 0xFFFFFFFFFFFFF000;
 }
```

Unfortunately, I don't really understand why .eh_frame is needed here, or why it's specified as NOLOAD. So, I can't really say for sure this patch won't cause problems of its own...

**Comment by missimer** [comment]
Hi @foxostro, glad you like the post.  Thanks for the improvement, I've tested your change with the latest Fedora and it works, while my original code is actually experiencing the same issue.

**Comment by missimer** [comment]
@foxostro I'm updating the blog post and would like to credit you with the fix if you have no objection.

**Comment by foxostro** [comment]
Sure, that’s cool. No objection here.

-Andrew
