### ISSUE TITLE
boot.S:1:0: error: code model kernel does not support PIC mode

### ISSUE THREAD

**Issue by Neetx** [missimer/x86-64-kernel-boot#2]
neetx@unknown:~/Scrivania/x86-64-kernel-boot$ make
make -C kernel all
make[1]: ingresso nella directory "/home/neetx/Scrivania/x86-64-kernel-boot/kernel"
gcc -fno-builtin -O2 -nostdinc -nostdlib -ffreestanding -g -Wall -Wextra -Werror -I. -MMD -mno-red-zone -mcmodel=kernel -Wa,--divide   -c -o boot.o boot.S
boot.S:1:0: error: code model kernel does not support PIC mode
 #include "arch/x86_64/gdt.h"
 
<incorporato>: set di istruzioni per l'obiettivo "boot.o" non riuscito
make[1]: *** [boot.o] Errore 1
make[1]: uscita dalla directory "/home/neetx/Scrivania/x86-64-kernel-boot/kernel"
Makefile:12: set di istruzioni per l'obiettivo "kernel" non riuscito
make: *** [kernel] Errore 2

I like this project, can you help to solve this?

**Comment by missimer** [comment]
Hi Neetx,

To help debug your issue could you run `uname -a` and `gcc --version`.  Thanks.

**Comment by Neetx** [comment]
Hi :)
I was from debian stretch, now i'm from manjaro, same error.

```[neetx@unknown x86-64-kernel-boot]$ make
make -C kernel all
make[1]: Entering directory '/home/neetx/software/x86-64-kernel-boot/kernel'
gcc -fno-builtin -O2 -nostdinc -nostdlib -ffreestanding -g -Wall -Wextra -Werror -I. -MMD -mno-red-zone -mcmodel=kernel -Wa,--divide   -c -o boot.o boot.S
cc1: error: code model kernel does not support PIC mode
make[1]: *** [<builtin>: boot.o] Error 1
make[1]: Leaving directory '/home/neetx/software/x86-64-kernel-boot/kernel'
make: *** [Makefile:12: kernel] Error 2

[neetx@unknown x86-64-kernel-boot]$ uname -a
Linux unknown 4.14.78-1-MANJARO #1 SMP PREEMPT Sun Oct 21 07:57:51 UTC 2018 x86_64 GNU/Linux

[neetx@unknown x86-64-kernel-boot]$ gcc --version
gcc (GCC) 8.2.1 20180831
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.```

**Comment by tay10r** [comment]
Same problem here. Same GCC version.
