### ISSUE TITLE
grub2-mkrescue

### ISSUE THREAD

**Issue by tay10r** [missimer/x86-64-kernel-boot#4]
On my system, Ubuntu 18.04, `grub2-mkrescue` is simply named `grub-mkrescue`.

Not sure how changing it would affect anyone else, but I believe at some point it should be switched to `grub-mkrescue` instead.

**Comment by missimer** [comment]
grub2-mkrescue is the name of the binary for Fedora.  I've made a fix to the Makefile to determine the binary dynamically.  Tested on Fedora and an Ubuntu docker image.
